// Mocks generated by Mockito 5.4.6 from annotations
// in all_paystack_payments/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:all_paystack_payments/all_paystack_payments_platform_interface.dart'
    as _i3;
import 'package:all_paystack_payments/payment_request.dart' as _i5;
import 'package:all_paystack_payments/payment_response.dart' as _i2;
import 'package:all_paystack_payments/webview_payment_handler.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePaymentResponse_0 extends _i1.SmartFake
    implements _i2.PaymentResponse {
  _FakePaymentResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AllPaystackPaymentsPlatform].
///
/// See the documentation for Mockito's code generation for more information.
class MockAllPaystackPaymentsPlatform extends _i1.Mock
    implements _i3.AllPaystackPaymentsPlatform {
  MockAllPaystackPaymentsPlatform() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> initialize(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [publicKey]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.PaymentResponse> initializePayment(
    _i5.PaymentRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#initializePayment, [request]),
            returnValue: _i4.Future<_i2.PaymentResponse>.value(
              _FakePaymentResponse_0(
                this,
                Invocation.method(#initializePayment, [request]),
              ),
            ),
          )
          as _i4.Future<_i2.PaymentResponse>);

  @override
  _i4.Future<String> getCheckoutUrl(_i5.PaymentRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#getCheckoutUrl, [request]),
            returnValue: _i4.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#getCheckoutUrl, [request]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<_i2.PaymentResponse> verifyPayment(String? reference) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPayment, [reference]),
            returnValue: _i4.Future<_i2.PaymentResponse>.value(
              _FakePaymentResponse_0(
                this,
                Invocation.method(#verifyPayment, [reference]),
              ),
            ),
          )
          as _i4.Future<_i2.PaymentResponse>);

  @override
  _i4.Future<_i2.PaymentResponse> getPaymentStatus(String? reference) =>
      (super.noSuchMethod(
            Invocation.method(#getPaymentStatus, [reference]),
            returnValue: _i4.Future<_i2.PaymentResponse>.value(
              _FakePaymentResponse_0(
                this,
                Invocation.method(#getPaymentStatus, [reference]),
              ),
            ),
          )
          as _i4.Future<_i2.PaymentResponse>);

  @override
  _i4.Future<bool> cancelPayment(String? reference) =>
      (super.noSuchMethod(
            Invocation.method(#cancelPayment, [reference]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<String?> getPlatformVersion() =>
      (super.noSuchMethod(
            Invocation.method(#getPlatformVersion, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);
}

/// A class which mocks [WebViewPaymentHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebViewPaymentHandler extends _i1.Mock
    implements _i7.WebViewPaymentHandler {
  MockWebViewPaymentHandler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.PaymentResponse> processPayment(String? checkoutUrl) =>
      (super.noSuchMethod(
            Invocation.method(#processPayment, [checkoutUrl]),
            returnValue: _i4.Future<_i2.PaymentResponse>.value(
              _FakePaymentResponse_0(
                this,
                Invocation.method(#processPayment, [checkoutUrl]),
              ),
            ),
          )
          as _i4.Future<_i2.PaymentResponse>);
}
