import 'enums.dart';
import 'payment_request.dart';

/// Payment request for bank transfer payments
class BankTransferRequest extends PaymentRequest {
  /// Bank account number (optional, will be generated by Paystack)
  final String? accountNumber;

  /// Bank code (optional, will be generated by Paystack)
  final String? bankCode;

  /// Bank name (optional, will be generated by Paystack)
  final String? bankName;

  /// Transfer type
  final BankTransferType transferType;

  BankTransferRequest({
    required super.amount,
    required super.currency,
    required super.email,
    super.reference,
    super.metadata,
    super.callbackUrl,
    this.accountNumber,
    this.bankCode,
    this.bankName,
    this.transferType = BankTransferType.account,
  }) : super(paymentMethod: PaymentMethod.bankTransfer);

  @override
  Map<String, dynamic> getSpecificJson() {
    return {
      'bank_transfer': {
        'account_number': accountNumber,
        'bank_code': bankCode,
        'bank_name': bankName,
        'transfer_type': transferType.name,
      },
    };
  }

  @override
  void validate() {
    super.validate();

    // For bank transfers, account details are usually generated by Paystack
    // So we don't require them in the request, but if provided, validate them
    if (accountNumber != null && accountNumber!.isEmpty) {
      throw ArgumentError('Account number cannot be empty if provided');
    }

    if (bankCode != null && bankCode!.isEmpty) {
      throw ArgumentError('Bank code cannot be empty if provided');
    }
  }
}
